import type { JobPosting } from '@/lib/types'

export const sampleJobs: JobPosting[] = [
  {
    id: 'sample_se_01',
    employerId: 'emirates-tech',
    employerName: 'Emirates Tech Solutions',
    title: 'Senior Software Engineer (React/Node)',
    description:
      'Join a high-performing engineering team building scalable web platforms for the aviation industry. Lead feature delivery and mentor developers.',
    requiredSkills: ['React', 'TypeScript', 'Node.js', 'REST APIs', 'AWS'],
    minExperience: 5,
    salaryMin: 18000,
    salaryMax: 28000,
    location: 'Dubai, UAE',
    industry: 'Technology',
    status: 'active',
    createdAt: new Date(),
  },
  {
    id: 'sample_pm_01',
    employerId: 'majid-digital',
    employerName: 'Majid Al Futtaim Digital',
    title: 'Product Manager (E-commerce)',
    description:
      'Own product roadmap for a regional e-commerce platform, collaborate cross-functionally to deliver impactful features and optimize conversion.',
    requiredSkills: ['Product Management', 'Analytics', 'A/B Testing', 'SQL', 'Agile'],
    minExperience: 4,
    salaryMin: 22000,
    salaryMax: 35000,
    location: 'Dubai, UAE',
    industry: 'Retail / E-commerce',
    status: 'active',
    createdAt: new Date(),
  },
  {
    id: 'sample_da_01',
    employerId: 'adnoc-analytics',
    employerName: 'ADNOC Analytics',
    title: 'Data Analyst',
    description:
      'Analyze operations and financial data to surface insights that drive efficiency and revenue growth. Build dashboards and reports.',
    requiredSkills: ['Python', 'SQL', 'Power BI', 'Excel', 'Statistics'],
    minExperience: 3,
    salaryMin: 12000,
    salaryMax: 18000,
    location: 'Abu Dhabi, UAE',
    industry: 'Energy',
    status: 'active',
    createdAt: new Date(),
  },
  {
    id: 'sample_mm_01',
    employerId: 'etisalat-marketing',
    employerName: 'Etisalat Marketing',
    title: 'Marketing Manager (Growth)',
    description:
      'Lead growth initiatives across paid channels and partnerships. Own GTM plans and performance marketing for key product lines.',
    requiredSkills: ['Performance Marketing', 'SEO', 'Paid Media', 'Analytics', 'GTM'],
    minExperience: 5,
    salaryMin: 15000,
    salaryMax: 25000,
    location: 'Dubai, UAE',
    industry: 'Telecom',
    status: 'active',
    createdAt: new Date(),
  },
  {
    id: 'sample_hr_01',
    employerId: 'dubai-airports',
    employerName: 'Dubai Airports',
    title: 'HR Generalist',
    description:
      'Support end-to-end HR operations including onboarding, employee relations, and policy compliance for a large, dynamic workforce.',
    requiredSkills: ['HR Operations', 'HRIS', 'Employee Relations', 'Onboarding'],
    minExperience: 3,
    salaryMin: 10000,
    salaryMax: 15000,
    location: 'Dubai, UAE',
    industry: 'Aviation',
    status: 'active',
    createdAt: new Date(),
  },
  {
    id: 'sample_cs_01',
    employerId: 'aramex',
    employerName: 'Aramex',
    title: 'Customer Success Manager (B2B)',
    description:
      'Drive client retention and growth by building strong relationships, proactively solving issues, and identifying expansion opportunities.',
    requiredSkills: ['Customer Success', 'Account Management', 'Analytics', 'Communication'],
    minExperience: 4,
    salaryMin: 12000,
    salaryMax: 20000,
    location: 'Dubai, UAE',
    industry: 'Logistics',
    status: 'active',
    createdAt: new Date(),
  },
  {
    id: 'sample_fe_01',
    employerId: 'dp-world-digital',
    employerName: 'DP World Digital',
    title: 'Frontend Engineer (UI/UX)',
    description:
      'Build elegant, performant frontend experiences with React and modern tooling. Collaborate with design to ship pixel-perfect UI.',
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'UX', 'Testing'],
    minExperience: 3,
    salaryMin: 16000,
    salaryMax: 24000,
    location: 'Dubai, UAE',
    industry: 'Logistics / Technology',
    status: 'active',
    createdAt: new Date(),
  },
  {
    id: 'sample_de_01',
    employerId: 'emaar-data',
    employerName: 'Emaar Data Platform',
    title: 'Data Engineer',
    description:
      'Design and maintain robust data pipelines and warehouses. Work with stakeholders to ensure data quality and availability.',
    requiredSkills: ['Python', 'SQL', 'ETL', 'Airflow', 'Cloud'],
    minExperience: 4,
    salaryMin: 18000,
    salaryMax: 26000,
    location: 'Dubai, UAE',
    industry: 'Real Estate / Technology',
    status: 'active',
    createdAt: new Date(),
  },
]
