name = "eiger-marvel-hr-plat"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"
type = "javascript"

[site]
bucket = "./dist"

[[routes]]
pattern = "emgc.sgctech.ai4"
zone_name = "sgctech.ai4"
